name: "Build documentation"

on: pull_request

jobs:
  build_doc:

    env:
      BASEDIR: ${{github.workspace}}/arrow-libs
      JAVA_OPTS: -Xms512m -Xmx1024m

    runs-on: macos-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Setup"
      run: brew install grep
    - name: "Set env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/set-env.sh
    - name: "Show env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/show-env.sh
    - name: "Create APIdoc"
      working-directory: arrow-libs
      run: ./gradlew dokka
    - name: "Validate documentation"
      working-directory: arrow-site
      run: ./gradlew runAnk
    - name: "Build site"
      working-directory: arrow-site
      run: |
         bundle install --gemfile Gemfile --path vendor/bundle
         bundle exec jekyll build -s build/site
