name: "Publish Arrow Stack (BOM file)"

on:
  push:
    branches:
    - main
    - release/**
    paths:
    - 'arrow-libs/**'
    - 'arrow-stack/**'
    - '.github/**'

jobs:
  publish-arrow-stack:

    env:
      BASEDIR: ${{github.workspace}}/arrow-libs
      SONATYPE_USER: ${{ secrets.SONATYPE_USER }}
      SONATYPE_PWD: ${{ secrets.SONATYPE_PWD }}
      ORG_GRADLE_PROJECT_signingKey: ${{ secrets.ORG_GRADLE_PROJECT_signingKey }}
      ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.ORG_GRADLE_PROJECT_signingPassword }}

    runs-on: macos-latest
    defaults:
      run:
        working-directory: arrow-stack

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Setup"
      run: brew install grep
    - name: "Set env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/set-env.sh
    - name: "Show env"
      run: ${GITHUB_WORKSPACE}/.github/scripts/show-env.sh
    - name: "Publish"
      run: |
        ./gradlew publish
        echo "$(cat $BASEDIR/gradle.properties | grep VERSION_NAME | cut -d'=' -f2) deployed!"
